### ISSUE TITLE
hi friends,  how did you generate the  hdr image images/SantasLittleHelper/HDR_tonemapped.jpg?  you genereate from this repo?  thanks?

### ISSUE THREAD

**Issue by zhangpengk** [fehimebetul/HDR-Project#3]

**Comment by fehimebetul** [comment]
if you ask me, images/SantasLittleHelper/ taken from here: https://web.ece.ucsb.edu/~psen/hdrvideo

**Comment by zhangpengk** [comment]
> if you ask me, images/SantasLittleHelper/ taken from here: https://web.ece.ucsb.edu/~psen/hdrvideo

thanks my friends
