### ISSUE TITLE
Getting error on line 395 DeghostingPeceKautz.cpp

### ISSUE THREAD

**Issue by M-Suzy** [fehimebetul/HDR-Project#4]
Hi, I am getting the following error on line 395 (using opencv3.4)

` error: (-215:Assertion failed) type2 == CV_64F && (sz2.height == 1 || sz2.height == 4) in function 'arithm_op`

**Comment by fehimebetul** [comment]
What is the number of channels and type of your image?

**Comment by M-Suzy** [comment]
3 channels rgb image

**Comment by fehimebetul** [comment]
Before, there was similar issue to yours. I honestly want to understand what is the reason because in my all machines it is working.Does it work when you apply the same process to any image in another piece of code, is this repo specific?

**Comment by fehimebetul** [comment]
> 3 channels rgb image

I want to learn the 

std::cout << image.channels() << "   " << image.type() << std::endl;

**Comment by M-Suzy** [comment]
Yep, I've tried both on the provided samples and on my samples and got the same error.

**Comment by fehimebetul** [comment]
> Yep, I've tried both on the provided samples and on my samples and got the same error.

Nope can you try the below with different project

cv::Mat Image = cv::imread("...png", CV_LOAD_IMAGE_COLOR); 
std::cout<<Image<<std::endl; Image = Image - cv::Vec3f(10.0f, 10.0f, 10.0f); 
std::cout<<"********************************"<<std::endl; 
std::cout<<Image<<std::endl; cv::waitKey(0); return 0

Do you get the same error?

**Comment by M-Suzy** [comment]
> > 3 channels rgb image
> 
> I want to learn the
> 
> std::cout << image.channels() << " " << image.type() << std::end .. after converting to

**Comment by M-Suzy** [comment]
> > Yep, I've tried both on the provided samples and on my samples and got the same error.
> 
> Nope can you try the below with different project
> 
> cv::Mat Image = cv::imread("...png", CV_LOAD_IMAGE_COLOR);
> std::cout<<Image<<std::endl; Image = Image - cv::Vec3f(10.0f, 10.0f, 10.0f);
> std::cout<<"********************************"<<std::endl;
> std::cout<<Image<<std::endl; cv::waitKey(0); return 0
> 
> Do you get the same error?

I will try and answer soon.

**Comment by M-Suzy** [comment]
So, tried just the following code and got the same error , the im.type() gives 21 after convertTo CV_32FC3, 
              `Mat imI = imread(filenames[i]);
		Mat im; imI.convertTo(im, CV_32FC3);
		im = im / 255.0;
		//imI = imI - Vec3f(10.0f, 10.0f, 10.0f);
		std::cout<<im.type()<<std::endl; 
		im= im- cv::Vec3f(10.0f, 10.0f, 10.0f);
		std::cout<<"********************************"<<std::endl;`

**Comment by M-Suzy** [comment]
and the same error without convertion to 32FC3, where the type gives 16 and channels 3

**Comment by fehimebetul** [comment]
ı think beacuse of opencv version my version now 3.4.9 got the same error, try below code it works.. I checked the results also...

    cv::Mat imI = ...png"); 
    cv::Mat im; imI.convertTo(im, CV_64FC3); 
    std::cout << im << std::endl;
    im = im / 255.0; 
    std::cout << imI << std::endl;
    std::cout<<"********************************"<<std::endl;
    imI = imI - cv::Scalar(10.0f,10.0f, 10.0f);
    std::cout << imI << std::endl;
    std::cout<<im.type()<<std::endl; 
    im= im- cv::Scalar(10,10, 10);

**Comment by M-Suzy** [comment]
Thanks, substracting cv::Scalar(10, 10, 10) works, and I've checked the previous code with opencv 4.2, the result is the same both for 3.4 and 4.2... Now, there is another problem on line 512
`(-5:Bad argument) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function 'arithm_op'`

**Comment by M-Suzy** [comment]
Ok, I've fixed it by changing `cv::Mat W = Mat::zeros(cv::Size(c, r), CV_64F);` to cv_32F
